### ISSUE TITLE
Can not use shops.

### ISSUE THREAD

**Issue by icecubepiso** [ZiggyJoJo/brp-fivem-appearance#3]
If i try to use any form of nh context menu it gives me this error. Im sorry, if im doing something wrong, but i never used it..
First option (for change clothes work) other options give me this errors. 

Thank you.
![obrazek](https://user-images.githubusercontent.com/33593306/127698959-8d9a0074-3cbb-48e2-bf9c-4d505f6875f6.png)

**Comment by ZiggyJoJo** [comment]
Did you make this change 
![](https://i.imgur.com/BHNaoJt.png)

**Comment by icecubepiso** [comment]
Oh im sorry.. im dump af today Sadge didn't see that

**Comment by icecubepiso** [comment]
Okay, that fix 1 problm.. of 2 now i get this, if i want save outfit.

![obrazek](https://user-images.githubusercontent.com/33593306/127700213-422ef313-e499-4833-bcff-e4b4c7764a6d.png)

**Comment by ZiggyJoJo** [comment]
Throw in print statements for each value so I can tall what's nil

**Comment by icecubepiso** [comment]
![obrazek](https://user-images.githubusercontent.com/33593306/127701494-0eff5146-62ff-4d0f-af4b-4ed2ad81e351.png)

**Comment by ZiggyJoJo** [comment]
Move the print statements that are after the event to just before so they trigger cause those are the ones that'll help

**Comment by icecubepiso** [comment]
![obrazek](https://user-images.githubusercontent.com/33593306/127702554-84aa41c2-be73-4837-9590-e05609f13763.png)
Here you go buddy

**Comment by ZiggyJoJo** [comment]
It looks like there's something wrong with your nh-keyboard is it running or did you edit that script in any way

**Comment by icecubepiso** [comment]
It is running, it gives me UI and i did not change it

**Comment by icecubepiso** [comment]
okay found problem
it looks like, if you download "release" it don't work.. now i download source and it's working 
sorry for my stupidty and THANK YOU for your help

**Comment by ZiggyJoJo** [comment]
Ok I pushed the source to release so no one else encounters this
